import './globals.css'
import { Inter } from 'next/font/google'
import { NowPlayingBar } from '@/components/now-playing-bar'
import { Dashboard } from '@/components/dashboard'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          <div className="grow">
            <Dashboard />
          </div>
          <div className="flex-none">
            <NowPlayingBar />
          </div>
        </div>
      </body>
    </html>
  )
}
